#!/bin/bash
# codex-reviewer.sh - Calls Codex CLI for code review
# Uses terminal's codex command directly, no API key configuration needed

set -e

# Helper function for streaming progress output
progress() {
  echo "[Codex Reviewer] $1" >&2
}

# Security: Sanitize input to prevent shell injection
sanitize_input() {
  # Remove potentially dangerous characters while preserving readability
  # Keep: alphanumeric, spaces, common punctuation, newlines
  echo "$1" | tr -d '\000-\010\013\014\016-\037' | head -c 100000
}

# Security: Create secure temp directory (user-only access)
SECURE_TEMP_DIR="${TMPDIR:-/tmp}/codex-reviewer-$(id -u)"
mkdir -p "$SECURE_TEMP_DIR"
chmod 700 "$SECURE_TEMP_DIR"

# ==================== Load Configuration ====================

PLUGIN_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_FILE="${CLAUDE_PROJECT_DIR:-.}/.claude/reviewer.json"

# Default configuration
MODEL="${REVIEWER_MODEL:-gpt-5.2-codex}"
TIMEOUT="${REVIEWER_TIMEOUT:-300}"
SCORE_THRESHOLD="${REVIEWER_SCORE_THRESHOLD:-85}"
BYPASS_APPROVAL="${REVIEWER_BYPASS_APPROVAL:-true}"
SAVE_HISTORY="${REVIEWER_SAVE_HISTORY:-true}"
LANG="${REVIEWER_LANG:-en}"

# Load from config file if exists
if [ -f "$CONFIG_FILE" ]; then
  MODEL=$(jq -r '.model // "gpt-5.2-codex"' "$CONFIG_FILE" 2>/dev/null || echo "$MODEL")
  TIMEOUT=$(jq -r '.timeout // empty' "$CONFIG_FILE" 2>/dev/null || echo "$TIMEOUT")
  SCORE_THRESHOLD=$(jq -r '.scoreThreshold // empty' "$CONFIG_FILE" 2>/dev/null || echo "$SCORE_THRESHOLD")
  BYPASS_APPROVAL=$(jq -r '.bypassApproval // true' "$CONFIG_FILE" 2>/dev/null || echo "$BYPASS_APPROVAL")
  SAVE_HISTORY=$(jq -r '.saveHistory // empty' "$CONFIG_FILE" 2>/dev/null || echo "$SAVE_HISTORY")
  LANG=$(jq -r '.lang // "en"' "$CONFIG_FILE" 2>/dev/null || echo "$LANG")
fi

# ==================== Parse Arguments ====================

CONTEXT=""
CHANGES=""
ITERATION=0
SESSION_ID="unknown"
CWD="."

QUICK_MODE=false

while [ $# -gt 0 ]; do
  case $1 in
    --context)
      CONTEXT="$2"
      shift 2
      ;;
    --changes)
      CHANGES="$2"
      shift 2
      ;;
    --iteration)
      ITERATION="$2"
      shift 2
      ;;
    --session-id)
      SESSION_ID="$2"
      shift 2
      ;;
    --cwd)
      CWD="$2"
      shift 2
      ;;
    --lang)
      LANG="$2"
      shift 2
      ;;
    --quick|-q)
      QUICK_MODE=true
      shift
      ;;
    *)
      shift
      ;;
  esac
done

# ==================== Language Settings ====================

if [[ "$LANG" == "zh"* ]]; then
  LANG_INSTRUCTION="请使用中文输出审查结果。"
  PASS_LABEL="通过"
  FAIL_LABEL="需要修改"
else
  LANG_INSTRUCTION="Please output the review result in English."
  PASS_LABEL="PASSED"
  FAIL_LABEL="NEEDS WORK"
fi

# ==================== Sanitize Inputs ====================

# Security: Sanitize context and changes to prevent injection
CONTEXT=$(sanitize_input "$CONTEXT")
CHANGES=$(sanitize_input "$CHANGES")

# ==================== Quick Mode ====================

if [ "$QUICK_MODE" = true ]; then
  # Quick mode: shorter prompt, faster response
  REVIEW_PROMPT="You are a code reviewer. Review this code briefly.
$LANG_INSTRUCTION

Code:
$CHANGES

Output format (Markdown):
## Score: [0-100]/100
## Verdict: [✅ PASS / ❌ NEEDS WORK]
## Issues (if any):
- [issue]
## Suggestions:
- [suggestion]"

  # Quick mode uses same model but shorter prompt
  MODEL="${REVIEWER_QUICK_MODEL:-gpt-5.2-codex}"
fi

# ==================== Build Review Prompt ====================

# Skip if quick mode already set the prompt
if [ "$QUICK_MODE" != true ]; then
REVIEW_PROMPT="You are a strict technical review expert (Codex Reviewer).
Your task is to review the solutions and code generated by Claude Code as a 'Senior Reviewer' role.

## Your Responsibilities
1. **Summarize** - Understand the overall approach, summarize the core implementation
2. **Find Risks** - Identify potential technical risks and security concerns
3. **Find Bugs** - Discover logic bugs, edge cases, missing exception handling
4. **Find Missing Items** - Check for unconsidered requirements or missing features
5. **Find Issues** - Predict potential runtime problems, performance bottlenecks, maintainability issues

## Review Standards
- Code Quality: Readability, maintainability, naming conventions
- Architecture Design: Module division, dependencies, extensibility
- Security: Input validation, permission control, sensitive data handling
- Robustness: Error handling, edge cases, fault tolerance
- Completeness: Requirement coverage, feature completeness, test coverage

## Current Iteration: $((ITERATION + 1))

## Conversation Context
$CONTEXT

## Recent Code Changes
$CHANGES

## Output Requirements
$LANG_INSTRUCTION

Please output the review result in the following Markdown format:

---

## 🔍 Codex Review Result

**Score:** [0-100]/100
**Verdict:** [✅ PASS / ❌ NEEDS WORK]

### 📝 Summary
[One paragraph summary of the solution]

### ⚠️ Risks
- [Risk 1]
- [Risk 2]

### 🐛 Issues / Bugs
- [Issue 1]
- [Issue 2]

### 📋 Missing Items
- [Missing 1]
- [Missing 2]

### 🔓 Security Vulnerabilities
- [Vulnerability 1]

### 💡 Suggestions
- [Suggestion 1]
- [Suggestion 2]

### 🔧 Must Fix (Blocking)
- [Must fix 1]
- [Must fix 2]

---

## Scoring Standards
- 90-100: Excellent, can pass
- 70-89: Good, minor issues that don't affect core functionality
- 50-69: Average, obvious issues that need fixing
- 0-49: Poor, serious issues that must be fixed

Only when score >= $SCORE_THRESHOLD AND 'Must Fix' section is empty, verdict can be '✅ PASS'.

Output the Markdown directly without code blocks."
fi  # End of full prompt mode

# ==================== Call Codex CLI ====================

# Security: Use secure temp directory
TEMP_OUTPUT="$SECURE_TEMP_DIR/review-${SESSION_ID}-${ITERATION}.md"
TEMP_PROMPT="$SECURE_TEMP_DIR/prompt-${SESSION_ID}-${ITERATION}.txt"

# Save prompt to temp file (with secure permissions)
echo "$REVIEW_PROMPT" > "$TEMP_PROMPT"
chmod 600 "$TEMP_PROMPT"

# Call Codex CLI
if ! command -v codex > /dev/null 2>&1; then
  progress "⚠️  Codex CLI not installed, skipping review"
  echo "## ⚠️ Codex CLI Not Installed"
  echo ""
  echo "Please install Codex CLI: npm i -g @openai/codex"
  exit 0
fi

# Build Codex command arguments
# Use 'codex exec' for non-interactive mode
CODEX_ARGS="exec --model $MODEL --output-last-message $TEMP_OUTPUT"

# Enable bypass approval if configured (recommended)
if [ "$BYPASS_APPROVAL" = "true" ]; then
  CODEX_ARGS="$CODEX_ARGS --dangerously-bypass-approvals-and-sandbox"
fi

progress "⏳ Waiting for Codex response (model: $MODEL, timeout: ${TIMEOUT}s)..."
progress ""

# Execute review with real-time streaming to stderr
# Codex output goes directly to stderr so user can see thinking process
CODEX_EXIT_CODE=0
timeout "$TIMEOUT" codex $CODEX_ARGS "$(cat "$TEMP_PROMPT")" >&2 || CODEX_EXIT_CODE=$?

progress ""

# Check exit status
if [ "$CODEX_EXIT_CODE" -eq 124 ]; then
  progress "⚠️  Review timed out after ${TIMEOUT}s"
elif [ "$CODEX_EXIT_CODE" -ne 0 ]; then
  progress "⚠️  Codex exited with code $CODEX_EXIT_CODE"
else
  progress "✓ Codex response received"
fi

# ==================== Output Result ====================

if [ -f "$TEMP_OUTPUT" ]; then
  progress "📊 Formatting review result..."
  progress ""

  # Output the markdown result to stderr (avoids folding)
  cat "$TEMP_OUTPUT" >&2
  echo "" >&2

  # Save to history if enabled
  if [ "$SAVE_HISTORY" = "true" ]; then
    HISTORY_DIR="$CWD/.claude/review-history/session_$SESSION_ID"
    mkdir -p "$HISTORY_DIR"
    cp "$TEMP_OUTPUT" "$HISTORY_DIR/iteration_$((ITERATION + 1)).md"
  fi
else
  progress "⚠️  Codex review timeout or failed"
  echo ""
  echo "## ⚠️ Review Timeout or Failed"
  echo ""
  echo "Codex failed to complete the review in time. Please try again later."
  echo ""
fi

# Clean up temp files
rm -f "$TEMP_PROMPT" "$TEMP_OUTPUT"
